Polidea/FlutterBleLib

- example/lib/ui/screen_on_boarding.dart
- lib/source/lib_core.dart
With this two commits I was able to run and use example application using Dart 2 mode.
I've tested by using following options from example app:
- scanning
- connecting
- canceling connection
- using is connected
- request mttu
- read rssi
- discover all services
- reading characteristic value
> Dart2 compatibility fix

- android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java
- android/src/main/java/com/polidea/flutter_ble_lib/constant/MethodName.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/BluetoothStateDelegate.java
- example/lib/test_scenario_view.dart
- example/lib/test_scenarios/base.dart
- example/lib/test_scenarios/bluetooth_state_toggle_scenario.dart
- example/lib/test_scenarios/sensor_tag_test_scenario.dart
- example/lib/test_scenarios/test_scenarios.dart
- lib/ble_manager.dart
- lib/flutter_ble_lib.dart
- lib/internal/bridge/bluetooth_state_mixin.dart
- lib/internal/bridge/internal_bridge_lib.dart
- lib/internal/bridge/lib_core.dart
- lib/internal/constants.dart
- lib/internal/flutter_ble_lib_mixins/bluetooth_state_mixin.dart
- lib/internal/internal_ble_manager.dart
Resolves #85 
Added new test scenario, refactored test scenario view, added new features
> Features: enabling and disabling Bluetooth

- android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java
Should be merged immediately after https://github.com/Polidea/MultiPlatformBleAdapter/pull/23
> Add changes necessary for supporting simulator

- android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java
> Add log level

- ios/Classes/FlutterBleLibPlugin.m
> Feature/[ios] Request MTU

- ios/Classes/FlutterBleLibPlugin.m
> Feature/[ios] Read RSSI

- ios/Classes/Util/FlutterErrorFactory.m
> [ios] Fix FlutterError creation

- lib/internal/bridge/lib_core.dart
> Add creation of Peripherals from restored state

- ios/Classes/Constants/ArgumentKey.h
- ios/Classes/Constants/ArgumentKey.m
- ios/Classes/FlutterBleLibPlugin.m
- lib/ble_manager.dart
- lib/internal/bridge/scanning_mixin.dart
- lib/internal/constants.dart
- lib/internal/internal_ble_manager.dart
Fixes #134 
@TomoLV please confirm it's working
> Add iOS specific argument to startPeripheralScan

- android/src/main/java/com/polidea/blemulator/DeviceContainer.java
- android/src/main/java/com/polidea/blemulator/DiscoveryResponseParser.java
- android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java
- android/src/main/java/com/polidea/blemulator/bridging/DartMethodCaller.java
- android/src/main/java/com/polidea/blemulator/bridging/constants/ArgumentName.java
- android/src/main/java/com/polidea/blemulator/bridging/constants/DartMethodName.java
- android/src/main/java/com/polidea/blemulator/bridging/constants/SimulationArgumentName.java
- example/lib/test_scenarios/sensor_tag_test_scenario.dart
- lib/blemulator/example/example_peripheral.dart
- lib/blemulator/internal/bridge/constants.dart
- lib/blemulator/internal/bridge/platform_to_dart_bridge.dart
- lib/blemulator/internal/internal.dart
- lib/blemulator/internal/simulation_manager.dart
- lib/blemulator/internal/simulation_manager_mixins/discovery_mixin.dart
- lib/blemulator/simulation/simulated_characteristic.dart
- lib/blemulator/simulation/simulated_peripheral.dart
> Add simulated discovery, services, characteristics

- android/src/main/java/com/polidea/blemulator/bridging/DartMethodCaller.java
- android/src/main/java/com/polidea/blemulator/bridging/JSONToBleErrorConverter.java
- lib/blemulator/blemulator.dart
- lib/blemulator/internal/bridge/platform_to_dart_bridge.dart
- lib/blemulator/internal/simulation_manager_mixins/error_checks_mixin.dart
- lib/blemulator/simulated_ble_error.dart
> Add error handling for simulated errors

- ios/Classes/ResponseConverter/CharacteristicResponseConverter.m
> [FIX][iOS] Fix monitor characteristic response json keys

- android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java
- android/src/main/java/com/polidea/blemulator/bridging/DartMethodCaller.java
- android/src/main/java/com/polidea/blemulator/bridging/constants/DartMethodName.java
- android/src/main/java/com/polidea/blemulator/bridging/decoder/CharacteristicDartValueDecoder.java
- lib/blemulator/example/example_peripheral.dart
- lib/blemulator/internal/bridge/constants.dart
- lib/blemulator/internal/bridge/platform_to_dart_bridge.dart
- lib/blemulator/internal/internal.dart
- lib/blemulator/internal/simulation_manager.dart
- lib/blemulator/internal/simulation_manager_mixins/characteristics_mixin.dart
- lib/blemulator/simulation/simulated_characteristic.dart
- lib/blemulator/simulation/simulated_peripheral.dart
[simulated-characteristic] add properties flags & make read() asynchronous
[simulated-characteristic] fix: add missing async keyword to read()
[blemulator] add: reading characteristics feature
[blemulator] fix: post merge changes
[blemulator] unify constants for metadata & params
[blemulator] remove unnecessary DartValueDecoder interface
[blemulator][characteristics] add isNotifying flag handling
[blemulator][characteristics] make value private field
[blemulator][characteristics] move characteristics methods to separate mixin
[blemulator][characteristics-mixin] extract characteristics finding logic to peripheral
> [example-peripheral] fix: characteristics uuids

- lib/blemulator/internal/simulation_manager_mixins/characteristics_mixin.dart
- lib/blemulator/internal/simulation_manager_mixins/discovery_mixin.dart
- lib/blemulator/internal/simulation_manager_mixins/error_checks_mixin.dart
- lib/blemulator/internal/simulation_manager_mixins/rssi_mixin.dart
- lib/blemulator/internal/simulation_manager_mixins/simulation_manager_base.dart
- lib/blemulator/simulation/simulated_peripheral.dart
> Add error checks to supported operations

- android/src/main/java/com/polidea/blemulator/bridging/DartValueHandler.java
- lib/blemulator/README.md
- lib/blemulator/internal/bridge/dart_to_platform_bridge.dart
- lib/blemulator/internal/scan_result.dart
- lib/blemulator/simulation/simulated_peripheral.dart
> Add README to BLEmulator

- .travis.yml
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
> [iOS] Configure iOS build

- lib/ble_manager.dart
- lib/blemulator/internal/internal.dart
- lib/blemulator/internal/simulation_manager_mixins/response_models.dart
- lib/blemulator/simulation/simulated_characteristic.dart
- lib/internal/constants.dart
Resolves #268, resolves #269, resolves #288
> Expose/hide types that need to be exposed/hidden

- lib/internal/bridge/characteristics_mixin.dart
- lib/internal/bridge/internal_bridge_lib.dart
- lib/internal/util/transformers.dart
- pubspec.yaml
- test/internal/bridge/lib_core_test.dart
- test/mock/mock_peripheral.dart
- test/util/ble_error_jsons.dart
> Cancel monitoring streams after error

- ios/Classes/FlutterBleLibPlugin.m
> [iOS][Fix] Remove unused Swift header import

- lib/internal/bridge/characteristics_mixin.dart
> Fix duplicated monitoring events

- ios/Classes/FlutterBleLibPlugin.m
- ios/Classes/Response/ServiceResponse.h
- ios/Classes/Response/ServiceResponse.m
- ios/Classes/ResponseConverter/CharacteristicResponseConverter.h
- ios/Classes/ResponseConverter/CharacteristicResponseConverter.m
- ios/Classes/ResponseConverter/ServiceResponseConverter.h
- ios/Classes/ResponseConverter/ServiceResponseConverter.m
> [iOS] Extract json parsing from main plugin class

- README.md
* pub.dev badge
* link to blemulator
> Added to the readme:

- android/src/main/java/com/polidea/flutter_ble_lib/converter/BleErrorJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/CharacteristicsDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/event/CharacteristicsMonitorStreamHandler.java
- lib/internal/bridge/characteristics_mixin.dart
> Fix cancelling characteristics monitoring

- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DeviceConnectionDelegate.java
> java casts properly integer value send as the connection timeout

- android/src/main/java/com/polidea/flutter_ble_lib/converter/BleErrorJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/CharacteristicsDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/event/CharacteristicsMonitorStreamHandler.java
- lib/internal/bridge/characteristics_mixin.dart
Somehow this PR got merged into develop, instead of master.
> [lib][characteristics] fix: monitoring errors handling (#309)

- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DeviceConnectionDelegate.java
> NPE when connection timeout is missing

- lib/internal/util/transaction_id_generator.dart
- test/internal/util/transcation_id_generator_test.dart
> fix transaction id generator

- CHANGELOG.md
- pubspec.yaml
> Release version 2.0.1

- README.md
> Update readme to include information about permissions

- android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java
> Drop unneeded get of activity

- example/ios/Podfile.lock
- ios/Classes/Event/AdapterStateStreamHandler.m
> Fix crash in observing Bluetooth adapter state on iOS

- REFERENCE.md
- lib/peripheral.dart
> Remove setting MTU to 23 in connect by default

- CHANGELOG.md
I forgot to add information about fixes in their respective pull requests in preparation for the next release.
Since it introduces a breaking change, I predict a bump in minor version.
> Add information about changes from merged PRs to changelog

- lib/internal/bridge/scanning_mixin.dart
- lib/scan_result.dart
- test/scan_result.dart
> Fix incorrect Manufacturer's Data

- CHANGELOG.md
- lib/internal/bridge/characteristics_mixin.dart
- lib/internal/bridge/lib_core.dart
- test/internal/bridge/lib_core_test.dart
> Delay start of characteristic monitoring until sink is created

- .gitignore
- CHANGELOG.md
- README.md
- REFERENCE.md
- android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java
- example/ios/Podfile.lock
- ios/Classes/Event/AdapterStateStreamHandler.m
- lib/internal/bridge/characteristics_mixin.dart
- lib/internal/bridge/lib_core.dart
- lib/peripheral.dart
- lib/scan_result.dart
- pubspec.yaml
- test/internal/bridge/lib_core_test.dart
- test/scan_result.dart
I'll later merge master into develop.
* **BREAKING** ScanResult.AdvertisementData.ManufacturerData has changed type from Int8List to Uint8List
* Fix issue with invalid value of manufacturer data in scan results
* Fix issue with initialising plugin from a service without an active activity
* Update README with information about permissions
* Fix issue with default value of MTU when connecting to a peripheral on Android
* Fix issue where first few notifications right after start of monitoring a characteristic could get lost
> Release 2.1.0

- README.md
- REFERENCE.md
- lib/scan_result.dart
> Clarify that two of ScanResult fields are iOS specific

- android/build.gradle
- android/gradle.properties
- android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/BleErrorJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/ConnectionStateChangeJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/DevicesResultJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/JsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/ScanResultJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/converter/SingleCharacteristicResponseJsonConverter.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/BluetoothStateDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/CharacteristicsDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DescriptorsDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DeviceConnectionDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DevicesDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/DiscoveryDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/LogLevelDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/MtuDelegate.java
- android/src/main/java/com/polidea/flutter_ble_lib/delegate/RssiDelegate.java
- example/android/app/build.gradle
> Migrate from Support Library to AndroidX

- android/build.gradle
- example/ios/Podfile.lock
- ios/flutter_ble_lib.podspec
> Update MBA to latest version

- example/pubspec.yaml
- pubspec.yaml
> Move example's dependency from plugin to example

- android/src/main/java/com/polidea/flutter_ble_lib/event/ConnectionStateStreamHandler.java
Add extra null check and synchronized block in async callback
Fixes #468
> [Android] Fix race condition in ConnectionStateStreamHanderl (#468)

- analysis_options.yaml
- lib/ble_manager.dart
- lib/peripheral.dart
- lib/scan_result.dart
- lib/src/_internal.dart
- lib/src/bridge/device_connection_mixin.dart
- pubspec.yaml
Fixed (what I hope) are the biggest static analysis issues on pub.dev.
> Added pedantic lib for better static analysis

- CHANGELOG.md
- android/build.gradle
- ios/flutter_ble_lib.podspec
- pubspec.yaml
> Bump version to 2.2.7

- lib/src/bridge/device_connection_mixin.dart
> Fix observing connection state

- .github/workflows/dart-flutter-package-analyzer.yml
- lib/src/bridge/device_connection_mixin.dart
This PR adds a Github Action that keeps track on metrics. It will fail the build if e.g. formatting error will be detected or the score will deteriorate by other means.
> Added “Dart/Flutter Package Analyzer” github action

- CHANGELOG.md
- lib/ble_manager.dart
- lib/src/internal_ble_manager.dart
> Add unsafe way of creating peripherals

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/polidea/flutter_ble_lib/constant/ArgumentKey.java
- example/ios/Podfile
- example/ios/Runner.xcodeproj/project.pbxproj
- ios/Classes/Constants/ArgumentKey.m
- ios/Classes/FlutterBleLibPlugin.m
- ios/flutter_ble_lib.podspec
- lib/peripheral.dart
- lib/src/_constants.dart
- pubspec.yaml
* Fix connection timeout on iOS
* Fix emitting current connection state on iOS
* Update MBA to 0.1.7:
* Fix lack of disconnection event on iOS when connection fails to be established
* Fix not all errors being passed through onError callbacks on Android (thanks, @eliaslecomte)
> Release v2.3.1

- example/ios/Podfile
- example/ios/Runner/Info.plist
- example/lib/devices_list/devices_bloc.dart
- ios/Classes/Event/ScanningStreamHandler.m
From discussions in tickets:
#580
#526
#532
> Improve example app

- README.md
> Add bluetooth-central key to README.md
